name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker image build & push to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: volevanya/nginx
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: latest
  run:
    name: Run
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Starting container with new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_VM_IP }}
          username: ${{ secrets.AWS_VM_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker stop $(sudo docker ps -a -q)
            sudo docker rmi -f volevanya/nginx:latest
            sudo docker run -p 80:80 -it -d volevanya/nginx:latest