name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker image build & push to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: volevanya/nginx
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          addLatest: true
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.AWS_VM_IP }}
      - name: Stop ALL running containers
        run: ssh ${{ secrets.AWS_VM_USER }}@${{ secrets.AWS_VM_IP }} docker stop $(docker ps -a -q)
      - name: Start NEW container
        run: ssh ${{ secrets.AWS_VM_USER }}@${{ secrets.AWS_VM_IP }} sudo docker run -p 80:80 volevanya/nginx


        docker stop $(docker ps -a -q)